project_structure:
  # match hardhat
  tests: test

compiler:
  solc:
    version: ${SOLC_VERSION}
    optimizer:
      enabled: true
      runs: ${SOLC_OPTIMIZER_RUNS}

    # Enable brownie to find installed contracts
    remappings:
      - "hardhat=node_modules/hardhat"
      - "@openzeppelin=node_modules/@openzeppelin"

networks:
  default: development
  development:
    # gas_price: 2_000_000_000
    cmd_settings:
      port: 8546
      gas_limit: 20_000_000
