@startuml
skinparam componentStyle rectangle

component "Wallet/WebUI" as UI


package "AAP" {
    issue_asset -down- UI
    transfer_asset -down- UI
    freeze_record -down- UI
    trace_asset -down- UI
    manage_keys_aap -down- UI
    view_balances_aap -down- UI
    view_txs_aap -down- UI
    manage_address_book_aap -down- UI
}
package "AAP <-> ETH" {
    sponsor_asset_type -down- UI
    wrap -down- UI
    unwrap -down- UI
}


[Relayer]
interface submit_tx
submit_tx -down- Relayer

[Ethereum Query Service] as QS
interface get_mt_proof_asset_record
interface get_frontier
interface get_txs_aap_since_block
interface get_latest_aap_state
get_txs_aap_since_block -down- QS
get_frontier -down- QS
get_mt_proof_asset_record -down- QS
get_latest_n_roots -down- QS
get_latest_aap_state -down- QS

' [Ethereum Access Provider] as EAP

[Owner's memos store] as OMS
interface fetch_memos
interface push_memo
fetch_memos -down- OMS
push_memo -down- OMS


[Map addresses<->enc pubkeys] as MAPADDRENC
interface register_addr_and_enc_pub_key
interface get_enc_pub_key_from_addr
register_addr_and_enc_pub_key -down- MAPADDRENC
get_enc_pub_key_from_addr -down- MAPADDRENC

Package "Smart Contracts" {

    [CAPE Smart Contract] as CAPESC
    interface submit_cape_block
    interface "sponsor_asset_type" as sponsor_asset_type_cape
    interface get_call_data
    note right: We are abusing the notation here as <b>get_call_data</b> \n is not a function of the CAPE Smart Contract. \nFetching the data of the transactions sent to the contract \n can be done by monitoring events on the ethereum blockchain.
    interface deposit_erc20
    submit_cape_block -down- CAPESC
    sponsor_asset_type_cape -down- CAPESC
    get_call_data -down- CAPESC
    deposit_erc20 -down- CAPESC

    [ERC20 Smart Contract] as ERC20
    interface approve
    interface transfer_from
    interface transfer
    interface balance

    approve -down- ERC20
    transfer -down- ERC20
    balance -down- ERC20
    transfer_from -down- ERC20

}

Relayer -down-> submit_cape_block
Relayer -down-> get_txs_aap_since_block
Relayer -down-> get_latest_n_roots
Relayer -down-> get_frontier
Relayer -down-> get_latest_aap_state

CAPESC -down-> transfer_from
CAPESC -down-> transfer

UI -down-> fetch_memos
UI -down-> submit_tx
UI -down-> sponsor_asset_type_cape
UI -down-> push_memo
UI -down-> deposit_erc20
UI -down-> approve
UI -down-> get_mt_proof_asset_record
UI -down-> get_txs_aap_since_block
UI -down-> register_addr_and_enc_pub_key
UI -down-> get_enc_pub_key_from_addr
UI -down-> get_latest_aap_state
QS -down-> get_call_data

@enduml
