[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
atomic_store = { version="0.0.2", registry="translucence" }
bincode = "1.3.3"
cap-rust-sandbox = { path = "../contracts/rust" }
dirs = "4.0"
# may switch to `ethers = "0.6.2"` in the future; keeping this for compatibility for now
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "2a40d01c938cdcc716071af5a0dc9b3242181c2c" }
jf-primitives = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "2a40d01c938cdcc716071af5a0dc9b3242181c2c" }
lazy_static = "1.4.0"
rand_chacha = { version = "0.3.1", features = ["serde1"] }
serde = { version = "1.0.123", features = ["derive", "rc"] }
serde_derive = "1.0.118"
serde_json = "1.0.61"
structopt = { version = "0.3" }
tide = "0.16.0"
tide-websockets = "0.4.0"
toml = "0.5"
tracing = "0.1.26"
tracing-subscriber = "0.3"
zerok_lib = { git = "ssh://git@github.com/SpectrumXYZ/spectrum.git", branch = "point-to-older-commit-4fec6c5ba8d15df94955195796cd016afc6cb232-with-new-jellyfish" }
