#!/usr/bin/env sh
set -eu

# Use `hdwallet-derive` to generate the addresses from a mnenmonic
ADDRESS_LIST="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266,0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

geth --dev \
     --http --http.addr 0.0.0.0 --http.vhosts "*" \
     --verbosity 1 \
     --mine --maxpeers 0 --nodiscover \
     --miner.gaslimit 25000000 \
     --allow-insecure-unlock \
     --password <(echo "") \
     --datadir /data --unlock $ADDRESS_LIST
