[package]
name = "cap-rust-sandbox"
version = "0.1.0"
edition = "2018"

[lib]
doctest = false

[dependencies]
jf-plonk = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish.git" }
jf-primitives = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish.git" }
jf-aap = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish-apps.git", rev = "eca7b7e85718c7770c24ad90dd34b8a07209a01b" }
jf-rescue = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish.git" }
jf-utils = { features=["std"], git = "ssh://git@github.com/SpectrumXYZ/jellyfish.git" }
reef = { git = "ssh://git@github.com/SpectrumXYZ/reef.git", rev = "28c52c6d14f39294bd099288d29d4f1052b7c144" }
zerok_lib = { git = "ssh://git@github.com/SpectrumXYZ/spectrum.git", rev = "59141a5a085e4d04cef81a01916f01ef3183b990", features = ["mocks"] }
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master" }
itertools = "0.10.1" # needed for jf-aap to compile
ark-std = "0.3.0"
serde_json = "1.0.67"
bincode = "1.3.3"
ark-serialize = "0.3.0"
ark-ff = "0.3.0"
ark-ec = "0.3.0"
ark-ed-on-bn254 = { version = "0.3.0", default-features = false }
hex = "0.4.3"
tokio = { version = "1.5", features = ["macros", "rt-multi-thread"] }
rand = "0.8.4"
serde = { version = "1.0.124", features = ["derive"] }
anyhow = "1.0.39"
ark-bn254 = "0.3.0"
num-traits = "0.2.14"
num-derive = "0.3.3"
rand_chacha = "0.3.1"
generic-array = { version = "0.14.4", features = ["serde"] }
sha3 = "0.9.1"
async-std = { version = "1.10.0", features = ["unstable", "attributes"] }
async-trait = "0.1.51"
futures = "0.3.16"
strum_macros = "0.20.1"
async-recursion = "1.0.0"

# copied from jellyfish
[dependencies.ark-poly-commit]
git = "https://github.com/arkworks-rs/poly-commit/"
rev = "cafc05e39692bbc5c383990063ad851f0b94a553"
default-features = false

[dev-dependencies]
proptest = "1.0.0"
