@startuml
autonumber

skinparam roundcorner 20

participant "Cape Contract" as C
participant "Ethereum Query Service" as EQS
participant "Alice's Wallet" as W_A
participant "Bob's Wallet" as W_B
participant "Relayer" as R
participant "Freezer" as F
participant "Auditor" as A


group Mint
    note left W_A: Alice mints some asset records, and she is the recipient
    W_A -> W_A: (mint_tx,[alice_memo]) := **build_mint_tx**(alice_address,fee, alice_coin, 50000, alice_address)
    W_A -> R: (mint_tx,[alice_memo])
    R -> R: b:= **create_new_block**(mint_tx,[alice_memo])
    R -> C: b
    C -> EQS: **new_block_event**(b,[])
    EQS -> W_A: **new_block_event**(b,[])
    EQS -> W_B: **new_block_event**(b,[])
    EQS -> A: **new_block_event**(b,[])
    EQS -> F: **new_block_event**(b,[])
    note left W_B: Bob receives no memo
    W_B -> W_B: [] := **fetch_memos_from**([alice_memo])
    note left W_A: Alice's wallet decrypts and stores the new asset record for further spending
    W_A -> W_A: [alice_memo] := **fetch_memos_from**([alice_memo])
    W_A -> W_A: **update_local_state_from**(alice_memo)
end group

@enduml
