name: ARM64 Build

on:
  push:
    branches:
      - main
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]"
  pull_request:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

env:
  RUST_TEST_THREADS: 4

jobs:
  build:
    runs-on: [self-hosted, arm64]
    container:
      image: ghcr.io/espressosystems/nix:main
      volumes:
        - github_nix:/nix
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        name: Cancel Outdated Builds
        with:
          access_token: ${{ github.token }}

      - uses: cachix/cachix-action@v12
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :

      - uses: actions/checkout@v4
        name: Checkout Repository

      - name: Work around git issue after git CVE-2022-24765 fix.
        run: git config --global --add safe.directory "$PWD"

      - name: Initialize Nix Shell
        run: nix-shell --run "echo Init"

      - name: Why does this work
        run: nix-shell --run "pnpm --recursive install"

      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          # todo: add nix key, for example:  nix-instantiate shell.nix | sha256sum  | head -c 10
          key: arm-cape-v5-${{ hashFiles('Cargo.lock') }}

      - name: Build all executables
        run: nix-shell --run "cargo build --release"

      - uses: actions/upload-artifact@v3
        with:
          name: arm-executables
          path: |
            target/release/address-book
            target/release/eqs
            target/release/faucet
            target/release/minimal-relayer
            target/release/wallet-api
            target/release/wallet-cli

  docker-wallet:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: actions/download-artifact@v3
        with:
          name: arm-executables
          path: target/release/

      - name: Set linker/loader to not be nix
        run: |
          patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 ./target/release/wallet-api
          patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 ./target/release/wallet-cli

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - uses: docker/setup-buildx-action@v3
        name: Setup Docker BuildKit (buildx)

      - uses: docker/login-action@v2
        name: Login to Github Container Repo
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/espressosystems/cape/wallet

      - uses: docker/build-push-action@v4
        name: Build and Push Docker
        with:
          context: .
          file: ./wallet.Dockerfile
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
