name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: nixos/nix:2.3.12
      volumes:
        - github_nix:/nix
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Install Tools
        run: |
          apk add git
          # alpine tar is not compatible: https://stackoverflow.com/a/64187955
          apk add --no-cache tar

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Initialize Nix Shell
        run: nix-shell --run "echo Init"

      - name: Configure Git
        run: |
          git config --global url."https://tl-ancients:${{ secrets.GITLAB_PAT }}@gitlab.com".insteadOf git://gitlab.com
          git config --global url."https://tl-ancients:${{ secrets.GITLAB_PAT }}@gitlab.com".insteadOf ssh://git@gitlab.com
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com".insteadOf git://github.com
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com".insteadOf ssh://git@github.com
          git config --global url."https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT }}/".insteadOf https://dl.cloudsmith.io/basic/

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          # todo: add nix key, for example:  nix-instantiate shell.nix | sha256sum  | head -c 10
          key: cape-v3-${{ hashFiles('Cargo.lock') }}

      - name: Linting
        run: nix-shell --run "prepend-timestamps lint-ci"

      - name: Run Tests
        run: nix-shell --run "prepend-timestamps cape-test-geth"

      - name: Generate Docs
        run: nix-shell --run "prepend-timestamps make-doc"
