name: Build Without Nix

on:
  push:
  #  branches:
  #    - main
  #  tags:
  #    # YYYYMMDD
  #    - "20[0-9][0-9][0-1][0-9][0-3][0-9]"
  pull_request:
  #schedule:
  #  - cron: "0 1 * * 1"
  workflow_dispatch:

jobs:
  build:
    env:
      RUST_TEST_THREADS: 4
      # TODO: remove this or increase this when contract size limit is not a problem
      SOLC_OPTIMIZER_RUNS: 20
      CONTRACTS_DIR: "${{ github.workspace }}/contracts"
      GOERLI_MNEMONIC: "test test test test test test test test test test test junk"
      GOERLI_URL: "https://goerli.infura.io/v3/<project_id>"
      HARDHAT_CONFIG: "${{ github.workspace }}/contracts/hardhat.config.ts"
      RINKEBY_MNEMONIC: "test test test test test test test test test test test junk"
      RINKEBY_URL: "https://rinkeby.infura.io/v3/<project_id>"
      TEST_MNEMONIC: "test test test test test test test test test test test junk"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
          run_install: true

      - name: pnpm install
        run: |
          pnpm --recursive install

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
          default: true
          components: rustfmt, clippy

      - name: Enable Rust Caching
        uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Add items to path
        run: |
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/contracts/node_modules/.bin" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/node_modules/.bin" >> $GITHUB_PATH

      - name: build-abi
        run: |
          python3 ./bin/build-abi

      - name: Lint Solidity
        run: |
          solhint -c "${GITHUB_WORKSPACE}/contracts/.solhint.json" -w 0 ${GITHUB_WORKSPACE}/contracts/**/*.sol

      - name: Cargo build release
        run: |
          cargo test --release --features=slow-tests --no-run
          cargo build --release
