name: Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 1 * * 1"
  workflow_dispatch:

env:
  RUST_TEST_THREADS: 4
  # TODO: remove this or increase this when contract size limit is not a problem
  SOLC_OPTIMIZER_RUNS: 20

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/espressosystems/nix:main
      credentials:
        username: ancient123
        password: ${{ secrets.ORG_GITHUB_PAT }}
      volumes:
        - github_nix_251:/nix
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        name: Cancel Outdated Builds
        with:
          access_token: ${{ github.token }}

      - name: Install Tools
        # git not installed by default
        # alpine default tar is not compatible: https://stackoverflow.com/a/64187955
        run: |
          apk add --no-cache tar git

      - name: Potential broken submodules fix
        run: |
          git checkout -f $(git -c user.name=x -c user.email=x@x commit-tree $(git hash-object -t tree /dev/null) < /dev/null) || :

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Initialize Nix Shell
        run: nix-shell --run "echo Init"

      - name: Configure Git
        run: |
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com".insteadOf git://github.com
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com".insteadOf ssh://git@github.com
          git config --global url."https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT }}/".insteadOf https://dl.cloudsmith.io/basic/

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          # todo: add nix key, for example:  nix-instantiate shell.nix | sha256sum  | head -c 10
          key: cape-v4-${{ hashFiles('Cargo.lock') }}

      - name: Linting
        run: nix-shell --run "prepend-timestamps lint-ci"

      - name: Build Slow Tests
        # Make sure the slow tests build, but don't run them (we have another workflow for that).
        run: nix-shell --run "prepend-timestamps cargo test --release --features=slow-tests --no-run"

      - name: Run Tests
        run: nix-shell --run "prepend-timestamps cape-test-geth"

      - name: Generate Docs
        run: nix-shell --run "prepend-timestamps make-doc"

      - name: Build Wallet
        run: nix-shell --run "cargo build -p cape_wallet --release"

      - uses: actions/upload-artifact@v2
        with:
          name: wallet-webserver
          path: |
            target/release/web_server

  docker:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          path: wallet-checkout

      - uses: actions/download-artifact@v2
        with:
          name: wallet-webserver
          path: wallet-checkout/target/release/

      - name: Set linker/loader to not be nix
        run: patchelf --set-interpreter /lib64/ld-linux-x86-64.so.2 wallet-checkout/target/release/web_server

      - uses: docker/setup-buildx-action@v1
        name: Setup Docker BuildKit (buildx)

      - uses: docker/login-action@v1
        name: Login to Github Container Repo
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        name: Generate Docker Metadata
        id: meta
        with:
          images: ghcr.io/espressosystems/cape/wallet

      - uses: docker/build-push-action@v2
        name: Build and Push Docker
        with:
          context: ./wallet-checkout/
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
