name: Testnet Build

on:
  schedule:
    - cron: '0 10 * * *' # run at 10:00 UTC
  workflow_dispatch:

jobs:
  nightly:
    name: Build for running tests against Rinkeby testnet # TODO: this workflow can probably be deduped as most of it mirrors the build from build.yml
    strategy:
      fail-fast: true
    runs-on: self-hosted
    container:
      image: ghcr.io/espressosystems/nix:main
      credentials:
         username: ancient123
         password: ${{ secrets.ORG_GITHUB_PAT }}
      volumes:
        - github_nix_251:/nix
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - name: Install Tools
        # git not installed by default
        # alpine default tar is not compatible: https://stackoverflow.com/a/64187955
        run: |
          apk add --no-cache tar git

      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Initialize Nix Shell
        run: nix-shell --run "echo Init"

      - name: Configure Git
        run: |
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com".insteadOf git://github.com
          git config --global url."https://ancient123:${{ secrets.ORG_GITHUB_PAT }}@github.com".insteadOf ssh://git@github.com
          git config --global url."https://dl.cloudsmith.io/${{ secrets.CLOUDSMITH_ENTITLEMENT }}/".insteadOf https://dl.cloudsmith.io/basic/

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          # todo: add nix key, for example:  nix-instantiate shell.nix | sha256sum  | head -c 10
          key: cape-v3-${{ hashFiles('Cargo.lock') }}

      - name: Run Tests Against Rinkeby Testnet
        run: nix-shell --run "RINKEBY_MNEMONIC='${{ secrets.RINKEBY_MNEMONIC }}' RINKEBY_URL='${{ secrets.RINKEBY_ENDPOINT }}' hardhat test --network rinkeby"
